spring:
  application:
    name: taco-cloud
  cassandra:
    keyspace-name: tacocloud
    schema-action: recreate #tables are dropped and recreated every time
    local-datacenter: datacenter1  #single node setup
    request:
      timeout: 10s
