spring.datasource.generate-unique-name=false
spring.datasource.name=tacocloud
spring.datasource.username=sa
spring.datasource.password=password

flyway.url=jdbc:h2:mem:tacocloud
flyway.user=sa
flyway.password=password
flyway.schemas=tacocloud

spring.thymeleaf.cache=false
